#!/bin/bash

# system by simmon
# simmon@nplob.com - siatbw-v0.01b

# siatbw program color code set.
RED='\033[0;31m'          # RED 빨강
BLUE='\033[0;34m'         # BLUE 파랑
WHITE='\033[0;37m'        # WHITE 하얀색
GREEN='\033[0;32m'        # GREEN 녹색

# program run.
echo "SCAN Your Disk INFO"
echo "status nvme"
echo "-------------------------------------------------------------------------"
fdisk -l|grep "/dev/nv"|grep Disk|cut -d '/' -f3
echo "-------------------------------------------------------------------------"
echo "staus sata or sas"
fdisk -l|grep "/dev/sd"|grep Disk|cut -d '/' -f3
echo "-------------------------------------------------------------------------"
echo "                                                                    "

  printf "CHECK or SCAN Disk Name ${GREEN} sda sdb sdc ${WHITE}\n"
  printf "OK, Enter your device name above: ${BLUE}"
read -a SYDND
  printf "${WHITE}Show - input Disk: ${SYDND}"
echo "                                                                         "
echo "TEST number of your Disk : ${#SYDND[*]}"
echo "                                                                         "
echo "-------------------------------------------------------------------------"

for SYDND in "${SYDND[@]}"

do

echo "-------------------------------------------------------------------------"
  printf "${WHITE}Input Device Name: ${BLUE} $SYDND ${WHITE}\n"
  printf "RAW Date Value - PROCESSING                       \n"
  BASinfo=$(smartctl -a /dev/${SYDND})
  rawinfo=`echo "$BASinfo"|awk '/Total_LBAs_Written/ {print $10*512/1024/1024/1024}'`
  NAME=`echo "$BASinfo"|awk '/Device Model/ {print $3 $4 $5 $6}'`
  On_Time=`echo "$BASinfo"|awk '/Power_On_Hours/ {print $10}'`
  Wear_Count=`echo "$BASinfo"|awk '/Wear_Leveling_Count/ {print $10}'`
  Lbs_Written=`echo "$BASinfo"|awk '/Total_LBAs_Written/ {print $10}'`
  Start_Stop_Count=`echo "$BASinfo"|awk '/Start_Stop_Count/ {print $10}'`
  Spin_Up_Time=`echo "$BASinfo"|awk '/Spin_Up_Time/ {print $10}'`
  Power_Cycle=`echo "$BASinfo"|awk '/Power_Cycle_Count/ {print $10}'`
  POR_Count=`echo "$BASinfo"|awk '/POR_Recovery_Count/ {print $10}'`
  NV_On_Time=`echo "$BASinfo"|awk '/Power On Hours/ {print $4}'`
  NV_Power=`echo "$BASinfo"|awk '/Power Cycles/ {print $3}'`
  NV_Model=`echo "$BASinfo"|awk '/Model Number/ {print $3 $4 $5 $6}'`
  NV_WRITE=`echo "$BASinfo"|awk '/Data Units Written/ {print $5 $6}'`
  NV_READ=`echo "$BASinfo"|awk '/Data Units Read/ {print $5 $6}'`
  TBW=`echo $rawinfo|awk '{print $1/1024}'`

  printf "On_Time: ${RED} ${NV_On_Time} ${On_Time} ${WHITE} Power_Cycle_Count: ${BLUE} ${NV_Power} ${Power_Cycle} ${WHITE}\n"
  printf "NVME Disk - DATA Units Written: ${BLUE} ${NV_WRITE} ${WHITE} DATA Units Read: ${BLUE} ${NV_READ} ${WHITE}\n"
  printf "SDD  Disk - Wear_Leveling_Count: ${BLUE} ${Wear_Count} ${WHITE} POR_Recovery_Count: ${BLUE} ${POR_Count} ${WHITE} lbs_written:${BLUE} ${Lbs_Written} ${WHITE}\n"
  printf "HDD  Disk - Spin_Up_Time: ${BLUE} ${Spin_Up_Time} ${WHITE} Start_Stop_Count: ${BLUE} ${Start_Stop_Count} ${WHITE}\n"
  printf "${BLUE}TBW-usage: $rawinfo GB ${RED}[ $TBW TB ] ${WHITE}\n"
  printf "${WHITE}TBW Device Name: ${GREEN} ${NV_Model} ${NAME} ${BLUE} ${SYDND} ${WHITE}test completed\n"
echo "-------------------------------------------------------------------------"
done
  printf " S I A T B W Program Terminated! ------------------------ ${WHITE} 💗system by simmon ${WHITE}\n"
echo "                                                                         "
